### ISSUE TITLE
Where / how to configure?

### ISSUE THREAD

**Issue by burggraf** [RekGRpth/pg_smtp#1]
What needs to be configured here in order to test this?  Pretty cool stuff!

**Comment by RekGRpth** [comment]
run `docker-compose up` and already done

**Comment by burggraf** [comment]
So it will send smtp mail through the local server?  Are there any issues with spam filters and such?

**Comment by RekGRpth** [comment]
> So it will send smtp mail through the local server?

Yes

**Comment by RekGRpth** [comment]
> Are there any issues with spam filters and such?

May be, but You may configure used opensmtpd server as You want.

**Comment by RekGRpth** [comment]
Main stuff of using own smtp server is report about delivering or not.

**Comment by RekGRpth** [comment]
But with pg_curl You may use any smtp server like gmail etc.

**Comment by burggraf** [comment]
Does this log the delivery attempt and success / failure anywhere?

**Comment by RekGRpth** [comment]
> Does this log the delivery attempt and success / failure anywhere?

Yes, in table `email`.

**Comment by burggraf** [comment]
Sweet, I'll check this out today!

**Comment by burggraf** [comment]
I just spun this up and fired off an email, and damn if it didn't work right off the bat!  But all emails go directly to spam boxes (at least for the gmail-based addressed I tried.)

But -- very cool!

**Comment by burggraf** [comment]
Using a valid from-email address it doesn't go to spam.  Wow.   Amazing.

**Comment by burggraf** [comment]
This seems to send everything in the to: field -- is it pretty easy to modify this to accept cc: and bcc: fields?

**Comment by RekGRpth** [comment]
> is it pretty easy to modify this

Yes, see https://github.com/RekGRpth/pg_smtp/blob/main/pg/setup.sql#L69

**Comment by burggraf** [comment]
Gotcha.  So I could implement `CC` and `BCC` same as `To`?

**Comment by RekGRpth** [comment]
> So I could implement `CC` and `BCC` same as `To`?

Yes, I didn't try so try

**Comment by burggraf** [comment]
I noticed the `result` column of email shows `{ok,ok,ok}` for mail that was sent ok, but returns `{sent}` for invalid email addresses.  Are there other return values here?

**Comment by RekGRpth** [comment]
> I noticed the `result` column of email shows `{ok,ok,ok}` for mail that was sent ok, but returns `{sent}` for invalid email addresses. Are there other return values here?

This set by me:

new - for new email
send - after send email

This takes from opensmtpd filter ([this](https://github.com/RekGRpth/pg_smtp/blob/main/smtp/smtpd/smtpd.awk#L7) and [that](https://github.com/RekGRpth/pg_smtp/blob/main/smtp/smtpd/smtpd.awk#L12)):

ok - if accepted email
permfail - if not accespted email
